# Generated by Django 5.2.17 on 2026-09-04 07:35

import django.db.models.deletion
import mailboard.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "permissions": (
                    ("board_owner", "Can add a mail receive character (board owner)"),
                    ("board_staff", "Can view tickets and respond to them"),
                    ("board_user", "Can create tickets via the web interface"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TicketCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "ticket categories",
            },
        ),
        migrations.CreateModel(
            name="BlacklistedCharacter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to unblock. Mails received while blocked stay ignored."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unblocked_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the character was last unblocked; older mails are ignored.",
                        null=True,
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="eveonline.evecharacter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoardOwner",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=True)),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen_mail_id",
                    models.BigIntegerField(
                        blank=True, help_text="Highest eve mail ID already processed for this character.", null=True
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="eveonline.evecharacter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PendingEveMail",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=1000)),
                ("content", models.TextField(max_length=10000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="eveonline.evecharacter"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "has_new_messages",
                    models.BooleanField(
                        default=False, help_text="Set when a new client message arrives, cleared when staff responds."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("web", "Web"), ("mail", "Eve mail"), ("staff", "Staff outreach")],
                        default="web",
                        max_length=8,
                    ),
                ),
                (
                    "mail_key",
                    models.CharField(
                        default=mailboard.models.generate_mail_key,
                        editable=False,
                        help_text="Secret used to authenticate eve mail replies to this ticket.",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailboard_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="eveonline.evecharacter"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="mailboard.ticketcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscordWebhook",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=500)),
                ("enabled", models.BooleanField(default=True)),
                ("mention", models.CharField(blank=True, max_length=128, null=True)),
                ("all_categories", models.BooleanField(default=False, help_text="Notify for tickets in any category.")),
                ("no_category", models.BooleanField(default=False, help_text="Notify for tickets without a category.")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Notify for tickets created in these categories.",
                        related_name="webhooks",
                        to="mailboard.ticketcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("client", "Client"), ("staff", "Staff")], max_length=8)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "mail_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ID of the eve mail this message was created from, if any.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="mailboard.ticket"
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
