# Generated by Django 5.2.17 on 2026-09-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordwebhook",
            name="mention",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
