# Generated by Django 5.2.17 on 2026-09-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('board_owner', 'Can add a mail receive character (board owner)'), ('board_staff', 'Can view tickets and respond to them'), ('board_user', 'Can create tickets via the web interface'), ('mailboard_admin', 'Can manage all tickets, locks and assignments'))},
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='While locked, only the assignee and mailboard admins can respond, change the category or close the ticket.'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='keywords',
            field=models.TextField(blank=True, default='', help_text='Comma-separated keywords. Tickets created via eve mail are automatically assigned the category whose keywords best match the mail subject.'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='type',
            field=models.CharField(choices=[('client', 'Client'), ('staff', 'Staff'), ('note', 'Staff note')], max_length=8),
        ),
    ]
