# Generated by Django 5.2.17 on 2026-09-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboard', '0002_discordwebhook_mention'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(unique=True)),
                ('character_name', models.CharField(blank=True, default='', help_text='Informational only; matching is done on the character ID.', max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True, help_text='Uncheck to unblock. Mails received while blocked stay ignored.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unblocked_at', models.DateTimeField(blank=True, editable=False, help_text='When the character was last unblocked; older mails are ignored.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_new_messages',
            field=models.BooleanField(default=False, help_text='Set when a new client message arrives, cleared when staff responds.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('mail', 'Eve mail'), ('staff', 'Staff outreach')], default='web', max_length=8),
        ),
    ]
