# Generated by Django 5.2.17 on 2026-09-04 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("mailboard", "0003_blacklistedcharacter_ticket_has_new_messages_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blacklistedcharacter",
            name="character_id",
        ),
        migrations.RemoveField(
            model_name="blacklistedcharacter",
            name="character_name",
        ),
        migrations.AddField(
            model_name="blacklistedcharacter",
            name="character",
            field=models.OneToOneField(
                default=0, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="eveonline.evecharacter"
            ),
            preserve_default=False,
        ),
    ]
